# Generated by Django 5.0 on 2023-12-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.TextField(default='country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dial_code',
            field=models.TextField(default='dial_code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(default='email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.TextField(default='firstname'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.TextField(default='lastname'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paypal_email',
            field=models.TextField(default='paypal_email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.TextField(default='phone number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(default='username'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='withdrawn',
            field=models.IntegerField(default=0),
        ),
    ]
