# Generated by Django 5.0 on 2023-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0002_userprofile_balance_userprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='message')),
                ('email', models.TextField(default='email')),
                ('username', models.TextField(default='username')),
            ],
        ),
    ]
