# Generated by Django 5.0 on 2023-12-29 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0003_userqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 33, 35, 825622)),
        ),
        migrations.AddField(
            model_name='availabletasks',
            name='task_name',
            field=models.TextField(default='firstname'),
        ),
    ]
