# Generated by Django 5.0 on 2023-12-29 10:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0004_availabletasks_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='how_to_important',
            field=models.TextField(default='how to important', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='how_to_info',
            field=models.TextField(default='how to info ', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='how_to_list',
            field=models.TextField(default='how to important', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='how_to_title',
            field=models.TextField(default='how to title', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='pay',
            field=models.TextField(default='how to info ', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='requirements',
            field=models.TextField(default='description', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='requirements_brief',
            field=models.TextField(default='requirements', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RemoTasker.availabletasks'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='task_description',
            field=models.TextField(default='description', null=True),
        ),
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 13, 31, 21, 613381)),
        ),
        migrations.AlterField(
            model_name='availabletasks',
            name='task_name',
            field=models.TextField(default='task name'),
        ),
    ]
