# Generated by Django 5.0 on 2023-12-29 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0005_taskinfo_how_to_important_taskinfo_how_to_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 13, 42, 17, 680190)),
        ),
    ]
