# Generated by Django 5.0 on 2023-12-29 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0006_alter_availabletasks_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 13, 44, 48, 484373)),
        ),
    ]
