# Generated by Django 5.0 on 2023-12-30 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0007_alter_availabletasks_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='how_to_important',
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='how_to_submit',
            field=models.TextField(default='how to submit', null=True),
        ),
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 9, 34, 14, 962757)),
        ),
    ]
