# Generated by Django 5.0 on 2023-12-30 10:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0013_alter_availabletasks_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 13, 24, 24, 998587)),
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='message')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 30, 13, 24, 24, 999587))),
                ('isRead', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RemoTasker.userprofile')),
            ],
        ),
    ]
