# Generated by Django 5.0 on 2023-12-30 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0014_alter_availabletasks_date_uploaded_usernotifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='balance',
            new_name='balanceActual',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pending',
            new_name='balanceHold',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dial_code',
            new_name='dialCode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='paypal_email',
            new_name='paypalEmail',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='withdrawn',
            new_name='withdrawPending',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='withdrawSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 13, 52, 35, 126732)),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 13, 52, 35, 126732)),
        ),
    ]
