# Generated by Django 5.0 on 2023-12-30 11:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0015_rename_balance_userprofile_balanceactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 14, 13, 35, 746060)),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 14, 13, 35, 746060)),
        ),
        migrations.CreateModel(
            name='WithdrawalRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('isApproved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 30, 14, 13, 35, 746060))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RemoTasker.userprofile')),
            ],
        ),
    ]
