# Generated by Django 5.0 on 2023-12-31 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoTasker', '0021_alter_availabletasks_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='timesViewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='availabletasks',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 22, 23, 253161)),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 22, 23, 253161)),
        ),
        migrations.AlterField(
            model_name='withdrawalrequests',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 22, 23, 253161)),
        ),
    ]
